import {
  Home,
  Users,
  PackageCheck,
  Truck,
  UserCheck,
  CircleDollarSign,
  PackageSearch,
  FileText,
  Settings,
  LogIn,
} from "lucide-react";

export const items = [
  {
    id: "main",
    title: "sidebar.main",
    name: "main",
    url: "/",
    icon: Home,
  },
  {
    id: "clients",
    title: "sidebar.clients",
    name: "clients",
    url: "/clients",
    icon: Users,
  },
  {
    id: "product-orders",
    title: "sidebar.product_orders",
    name: "product orders",
    url: "/product-orders",
    icon: PackageCheck,
  },
  {
    id: "shipments",
    title: "sidebar.shipments",
    name: "shipments",
    url: "/shipments",
    icon: Truck,
  },
  {
    id: "delivery-men",
    title: "sidebar.delivery_men",
    name: "delivery men",
    url: "/delivery-men",
    icon: UserCheck,
  },
  {
    id: "fix-transactions",
    title: "sidebar.transactions",
    name: "fix transaction",
    url: "/fix-transactions",
    icon: CircleDollarSign,
  },
  {
    id: "product-management",
    title: "sidebar.product_management",
    name: "product management",
    url: "/product-management",
    icon: PackageSearch,
  },
  {
    id: "reports",
    title: "sidebar.reports",
    name: "reports",
    url: "/reports",
    icon: FileText,
  },
  {
    id: "settings",
    title: "sidebar.settings",
    name: "settings",
    url: "/settings",
    icon: Settings,
  },
  {
    id: "login",
    title: "sidebar.login",
    name: "login",
    url: "/login",
    icon: LogIn,
  },
];
